#!/bin/bash

# 0 significa que só vai compilar, enquanto que 1 significa que também vai executar
if [ $2 -eq 0 ]; then 
    g++ $1.c -o $1
elif [ $2 -eq 1 ]; then
    g++ $1.c -o $1; ./$1
else 
    echo "Um erro aconteceu! Tente novamente."
fi